apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels: { app: website }
spec:
  replicas: 1
  selector: { matchLabels: { app: website } }
  template:
    metadata: { labels: { app: website } }
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: website
        image: ghcr.io/exea-centrum/website-argocd-k8s-githubactions-kustomize-kyverno04:latest
        ports:
        - containerPort: 8080
