apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kaniko-build-job.yaml # Dodano Job Kaniko
- kaniko-sa.yaml        # Dodano Service Account (opcjonalnie)
- postgres-deployment.yaml
- postgres-service.yaml
- website-deployment.yaml
- website-service.yaml

secretGenerator:
- name: postgres-secret
  literals:
  - password=bardzotajnehaslo123 
  
# UWAGA: Kaniko Job musi być usunięty przed wdrożeniem, ponieważ nie jest
# komponentem trwałym. Dodamy tu adnotację ArgoCD do pominięcia.
# W kustomization.yaml Production dodamy adnotację:
# argocd.argoproj.io/sync-wave: "-1" dla Job'a, aby wykonał się pierwszy.
