apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - postgres.yaml

images:
  - name: ghcr.io/exea-centrum/website-argocd-k8s-githubactions-kustomize-kyverno04
    newTag: latest
