apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: davtrogr

resources:
- ../base
- namespace.yaml
- ingress.yaml
- servicemonitor.yaml

# Zmiana obrazu na publiczny/rejestrowy
images:
- name: website-argocd-k8s-githubactions-kustomize-kyverno04:placeholder
  newName: ghcr.io/exea-centrum/website-argocd-k8s-githubactions-kustomize-kyverno04
  newTag: latest # Będzie aktualizowane przez GitHub Actions po każdym buildzie

namePrefix:
