apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "supersecurepassword"
  DATABASE_URL: "postgres://appuser:supersecurepassword@postgres:5432/appdb?sslmode=disable"
