apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: davtrogr-website
  namespace: argocd 
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    repoURL: https://github.com/exea-centrum/website-argocd-k8s-githubactions-kustomize-kyverno04.git # Pamiętaj o zmianie właściciela na Twój!
    targetRevision: HEAD
    path: manifests/production # Ścieżka do głównego kustomization.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: davtrogr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # Kaniko potrzebuje tego, aby ArgoCD wiedziało, że Deployment
    # może być niedostępny (np. obraz jeszcze nie istnieje)
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Użyteczne dla kustomize i patches
