apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: website-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: website
  endpoints:
    - port: 80
      path: /metrics
      interval: 15s
