name: Build and Deploy to ArgoCD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/exea-centrum/website-argocd-k8s-githubactions-kustomize-kyverno04:${{ github.sha }} .

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push image
        run: docker push ghcr.io/exea-centrum/website-argocd-k8s-githubactions-kustomize-kyverno04:${{ github.sha }}

      - name: Update Kustomize image tag
        uses: imranismail/setup-kustomize@v2
      - run: |
          cd manifests/base
          kustomize edit set image ghcr.io/exea-centrum/website-argocd-k8s-githubactions-kustomize-kyverno04=ghcr.io/exea-centrum/website-argocd-k8s-githubactions-kustomize-kyverno04:${{ github.sha }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add manifests/base/kustomization.yaml
          git commit -m "update image tag to ${{ github.sha }}"
          git push
