name: CI/CD Build & Deploy
on:
  push:
    branches: [ "main" ]
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  KUSTOMIZE_PATH: manifests/production
  PLACEHOLDER: website-argocd-k8s-githubactions-kustomize-kyverno04:placeholder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag
        id: tag
        run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.TAG }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Update Kustomize Tag
        uses: karancode/kustomize-image-tag-update@v1
        with:
          kustomize_path: ${{ env.KUSTOMIZE_PATH }}
          image_name: ${{ env.PLACEHOLDER }}
          new_tag: ${{ steps.tag.outputs.TAG }}

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'manifests/production/kustomization.yaml'
          message: "Update image tag to ${{ steps.tag.outputs.TAG }}"
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
