name: Build and Deploy to GHCR

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'go.mod'

permissions:
  contents: write
  packages: write

env:
  IMAGE_REPOSITORY: ghcr.io/${{ github.repository }}
  KUSTOMIZE_PATH: manifests/production
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: tag
        run: echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_REPOSITORY }}:${{ steps.tag.outputs.TAG }}
            ${{ env.IMAGE_REPOSITORY }}:latest

      - name: Update Kustomize image tag
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
          kustomize edit set image ${{ env.IMAGE_REPOSITORY }}=${{ env.IMAGE_REPOSITORY }}:${{ steps.tag.outputs.TAG }} --kustomization ${{ env.KUSTOMIZE_PATH }}
          cat ${{ env.KUSTOMIZE_PATH }}/kustomization.yaml

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Update image tag to ${{ steps.tag.outputs.TAG }}"
          add: '${{ env.KUSTOMIZE_PATH }}/kustomization.yaml'
