name: Build and Deploy
on:
  push:
    branches: [ "main" ]
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE="ghcr.io/${{ github.repository }}:$(git rev-parse --short HEAD)"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Update Kustomize Image
        run: |
          cd manifests/production
          kustomize edit set image ghcr.io/${{ github.repository }}=${IMAGE}
          cd ../..
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add manifests/production/kustomization.yaml
          git commit -m "Update image to ${IMAGE}"
          git push
